; GigaSeq - MIDI sequencer for Arduino Giga

[platformio]
name = GigaSeq
description = MIDI sequencer for Arduino Giga

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 9600

build_src_filter =
    +<*>
    -<desktop/>


build_flags =
    -DMBED_HEAP_STATS_ENABLED=1
    -I src
    -I src/engine
    -I src/const

lib_deps =
    arduino-libraries/Arduino_GigaDisplay_GFX@^1.1.0
    fortyseveneffects/MIDI Library@^5.0.2
